# Generated by Django 4.2.7 on 2023-11-26 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_birthday_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="re_password",
            new_name="rePassword",
        ),
    ]
