# Generated by Django 4.2.7 on 2023-11-26 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_re_password_user_repassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rePassword",
        ),
    ]
