# Generated by Django 4.2.7 on 2023-11-27 19:43

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                max_length=254,
                unique=True,
                validators=[accounts.models.validate_email],
            ),
            preserve_default=False,
        ),
    ]
