# Generated by Django 5.0 on 2023-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
